version: "3.4"

services:
  dappnode-watchgit.eth:
    build: ./build
    image: "dappnode-watchgit:0.1.0"
    restart: always
    volumes:
      - "/usr/src/dappnode/DNCORE/:/usr/src/app/DNCORE/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true
    environment:
      CONFIG_PATH: "/usr/src/app/DNCORE/watchgit.config"
      GITHUB_TOKEN: ""
